BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB BBBB BBBBBBBBBB BBBB BBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXXXXX XXX X XXXXXXXXXX XXXXX XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB

BBBBB BBBBB
 X 
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBXX gettext(u'Home') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Sdfs') XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB

BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Use my location') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXX gettext(u'or') XXXXXXX XXXXXXXXXX
                XXXXXXXXX

                

                
                
                

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX gettext(u'Filter by group') XXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBB
                BBBBB
            XXXXXXX

                XXXXXXX XXXXXXXXX
                    XXX XXXXXXXXXX XXXXXXXXXXXXX
                BBB BBB BB BBBBBBBB
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBB BBBBBBXX
                        
                    XXXX
                XXXXX
                BBBBBB
                XXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX

                BBB BBB BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX
                        BB BBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFF XXXXXXXXX
                        BBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBB BBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'View sdf details') XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            BB BBBBBBBBB
                                BBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBB BB BB
                                XX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            BBBB
                                XX XXXXXXXXXXXX
                            BBBBB
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXX
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX
                        XXXXXX
XXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXX
XXX
                    XXXXXX
                XXXXXX
                BBBBBB
            BBBB
                XXX gettext(u'No sdfs found in the area.') XXXX
            BBBBB
        XXXXXX
        BBBB
        XXX gettext(u'No sdf data available.') XXXX
        BBBBB
    XXXXXX
XXXXXX

BBBBBBBB

BBBBB BBBBBBBBBBBB
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBB
    BB BBBBBBBB
        XXX XXXXXXX X X
            BBB BBB BB BBBBBBBB
            X
                XXXXXXX XFFFFFFFFXX
                XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFX FFFFFFFFFFXX
                XXXXXXXXXXX XBB BBBBBBBBBBBBBBXX
                XXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXXXXX XFFFFFFFFXX
                XXXXXXXXXXX XFFFFFFFFXX
                XXXXXX XFFFFFFFFXX
                XXXXXXXX XFFFFFFFFXX
                XXXXXXXX XBB BBBBBBBBBFFFFFFFFBBBBBXX
                XXXXXXXX XFFFFFX
            X BB BBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBXBBBBB
            BBBBBB
        XX
        BB BBBBBBBBB BBB BBBBBBBB
            XXX XXX X XXX XXXXXXXXXXXXXXXXXXXX XX
        BBBB
            XXX XXX X XXXXX
        BBBBB
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    BBBBB
BBBBBBBB
