# Generated by Django 3.2.16 on 2023-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='An image with a display inquiry of zero will be the primary image for a sdu', verbose_name='Display inquiry'),
        ),
        migrations.AlterField(
            model_name='sdurecommendation',
            name='ranking',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Determines inquiry of the sdus. A sdu with a higher value will appear before one with a lower ranking.', verbose_name='Ranking'),
        ),
    ]
