# Generated by Django 3.2.16 on 2023-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='num_inquiries',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Inquiries'),
        ),
    ]
