BBBB BBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBB
        BBBBBBB BBBBBBB BB BBBBBBB BB BBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBBBB
                    XXXX
                        XXXXFFFFFFFFFFFFFFFFFXXXXX
                        XXXX
                            BBB BBBBBB BB BBBBBBBBBBBB
                                FFFFFFFFFFFFFFFFFFFFFFXXXXX
                            BBBBBB
                        XXXXX
                    XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
    BBBBB
BBBBBBB
