BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
 gettext(u'Delete sdf group?')  X 
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Sdf groups') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete?') XXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
     gettext(u'Delete sdf group?') 
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n            <p>Delete sdf group <strong>%(group_name)s</strong> - are you sure?</p>\n            ') 
            SSSSSSSSS SSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS S SSS SSS SSSSSSSSS
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
             gettext(u'or') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'cancel') XXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB
