BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Sdfs') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete?') XXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
     gettext(u'Delete sdf?') 
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n            <p>Delete sdf <strong>%(sdf_name)s</strong> - are you sure?</p>\n            ') 
            SSSSSSSSS SSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSS S SSS SSS SSSSSSSSS
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Delete') XXXXXXXXX
             gettext(u'or') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'cancel') XXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB
