BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXBBBBBBBB

BBBBB BBBBB
 X 
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Sdfs') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB

BB BBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
     gettext(u'Your submitted data did not validate - please correct the below errors and resubmit.') 
XXXXXX
BBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX
        BBBBBB
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Sdf details') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB
            XXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB
        XXX
        BBBBBBBB BBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Contact details') XXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB
        BBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Address') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBB BBBBBBBBBBBBBB
        BBBB BBBBBBBBBBBBBBBBB
            
            BBB BBBBBBBBBBBB BB BBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB

                BBB BBBBB BB BBBBBBBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBB
            BBBBBB
        BBBBBBB
        BBBBBBBB BBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Location') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
        XXX
             gettext(u'\n            Enter an address in the location input and select your address from the options that appear.\n            You can drag the marker around on the map to fine-tune the location.\n            ') 
            SSSSS SS SSSSSSS SS SSS SSSSSSSS SSSSS SSS SSSSSS SSSS SSSSSSS SSSS SSS SSSSSSS SSSS SSSSSSS
            SSS SSS SSSS SSS SSSSSS SSSSSS SS SSS SSS SS SSSSSSSSS SSS SSSSSSSSS
            
        XXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Please select a location for your sdf.') XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXXX
        BBBBBBBB BBBBBBBBBBBBBBB
    XXXXXX
XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Opening hours') XXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBBB
        
        BBBB BBBBBBBBBBBBBBBBBBB
            
            BBB BBBBBBB BB BBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBB
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                BBBBBB
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                      
                    XXXXXX
                  XXXXXX

                  BBB BBBB BB BBBBBBB
                  XXXX XXXXXXXXXX XXXX XXXXXXXXXXBB BBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBB XXXXXXBBBBBXX

                    XXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX
                    XXXXXX

                    

                    BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                      BBB BBBBB BB BBBB
                        BB BBBBBBBBBBBB
                          X
                          BBB BBB BB BBBBBBBBBBBBBBBBBB
                          XXX XX
                        BBBBB
                      BBBBBB

                      
                      BB BBBBBBBBBBBBBBBBBBBBB
                        
                        XXX XX
                      BBBBB
                      XXXXXX
                    XXXXXX
                    BBBBB
                  XXXXXX
                  BBBBBB

                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX

                
            XXXXXX
            BBBBBB
        BBBBBBB
        BBBBBBBB BBBBBBBBBBBBBBBBBBBB
    XXXXXX
XXX
    BBBBB BBBBBBBBBBBBBBBBBB
    BBBBBBBB BBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
             gettext(u'or') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'cancel') XXXX
        XXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    
    XXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBB
