BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBXXXXBBBBBBBB

BBBBB BBBBB
 X 
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Sdf groups') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
XXXXXX
BBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Sdf Group Details') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Save sdf group') XXXXXXXXX
             gettext(u'or') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'cancel') XXXX
        XXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB
