BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBXXXXBBBBBBBB
BBBBB BBBBB
 gettext(u'Sdf management')  X 
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Sdf groups') XXXXX
    XXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Create new sdf group') XXXX
    XXXX gettext(u'Sdf Groups') XXXXX
XXXXXX
BBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX
            XXXX gettext(u'Group Name') XXXXX
            XXXX gettext(u'Sdf') XXXXX
            XXXX gettext(u'Street') XXXXX
            XXXX gettext(u'City') XXXXX
            XXXX gettext(u'Post Code') XXXXX
            XXXX gettext(u'State') XXXXX
            XXXX gettext(u'Country') XXXXX
            XXXXXXXXX
        XXXXX
        BBB BBBBB BB BBBBBBBBBB
            BBB BBB BB BBBBBBBBBBBBBB
            XXXX
                BB BBBBBBBBBBBBB
                    XXX XXXXXXXXXFFFFFFXXXXXXX
                BBBBB
                XXXXXXXXX
                BBBB BBBBBBBBBBBBBBBBBBB
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                BBBBBBB
                BB BBBBBBBBBBBBB
                    XXX XXXXXXXXXFFFFFFXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX gettext(u'Edit') XXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX gettext(u'Delete') XXXX
                    XXXXX
                BBBBB
            XXXXX
            BBBBB
            XXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXX gettext(u'No sdfs assigned to this group.') XXXXX
                XXXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX gettext(u'Edit') XXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX gettext(u'Delete') XXXX
                XXXXX
            XXXXX
            BBBBBB
        BBBBBB
    XXXXXXXX

    BB BBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
XXXXXXX

BBBB
    XXX gettext(u'No sdf groups found.') XXXX
BBBBB

BBBBBBBB BBBBBBBBBBBBBBBBB
