# Generated by Django 3.2.16 on 2023-01-08 05:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='Slug')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SdfGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SdfAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country')),
                ('sdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='sdfs.sdf', verbose_name='Sdf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sdf',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sdfs', to='sdfs.sdfgroup', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='SdfStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number in stock')),
                ('num_allocated', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number allocated')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='In sdf location')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('sdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='sdfs.sdf', verbose_name='Sdf')),
                ('sdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdf_stock', to='catalogue.sdu', verbose_name='Sdu')),
            ],
            options={
                'verbose_name': 'Sdf stock record',
                'verbose_name_plural': 'Sdf stock records',
                'abstract': False,
                'unique_together': {('sdf', 'sdu')},
            },
        ),
    ]
