# Generated by Django 3.2.16 on 2023-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdfaddress',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street number'),
        ),
        migrations.AlterField(
            model_name='sdfaddress',
            name='line4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='sdfaddress',
            name='line5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='sdfaddress',
            name='line6',
            field=models.CharField(blank=True, max_length=255, verbose_name='District'),
        ),
    ]
