# Generated by Django 3.2.16 on 2023-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0002_auto_20230118_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdf',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sdf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sdf-images', verbose_name='Image'),
        ),
    ]
