# Generated by Django 3.2.16 on 2023-01-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0004_sdfsdu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdfsdu',
            options={'verbose_name': 'Sdf Sdu details', 'verbose_name_plural': 'Sdf Sdu details'},
        ),
        migrations.AlterField(
            model_name='sdfsdu',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='AppId'),
        ),
        migrations.AlterField(
            model_name='sdfsdu',
            name='sdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sdfs.sdfsdu', verbose_name='SdfId'),
        ),
    ]
