# Generated by Django 3.2.16 on 2023-01-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0005_auto_20230130_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdfsdu',
            name='sdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdfs.sdfsdu', verbose_name='SdfId'),
        ),
    ]
