# Generated by Django 3.2.16 on 2023-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0009_alter_sdfsdu_sdfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdfsdu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
