# Generated by Django 3.2.16 on 2023-02-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0010_sdfsdu_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdfsdu',
            name='building',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='sdfsdu',
            name='district',
            field=models.CharField(default='', max_length=25, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='sdfsdu',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='AppId'),
        ),
    ]
