# Generated by Django 3.2.16 on 2023-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdfs', '0012_auto_20230223_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdfsdu',
            name='evaluate_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='評估租金'),
        ),
        migrations.AddField(
            model_name='sdfsdu',
            name='street',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='街道'),
        ),
    ]
